version: '3'
services:
  scibite-ai:
    container_name: scibite-ai
    image: scibite/scibiteai:latest
    ports:
      - 8000:8000
    volumes:
      - ./models:/models

  tf-serving:
    container_name: tf-serving
    build:
      context: ./
      dockerfile: ./config/tfserving.Dockerfile
    ports:
      - 8500:8500
      - 8501:8501
    volumes:
      - ./models/:/models/
    command:
      - '--model_config_file=/models/model_config.config'
      - '--model_config_file_poll_wait_seconds=-1'
      - '--enable_batching=true'
      - '--batching_parameters_file=/models/batch_params.pb'

  redis:
    container_name: redis-db
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  cron-runner:
    container_name: cron-runner
    build:
      context: ./
      dockerfile: ./config/cron.Dockerfile
    volumes:
      - ./models/:/models/
    entrypoint: /entrypoint.sh
