version: '3'
services:

  scibite-ai:
    container_name: scibite-ai
    image: scibite/scibiteai-dev:2.0-rc
    ports:
      - 8000:8000
    volumes:
      - ./models:/SciBiteAI

  tf-serving:
    container_name: tf-serving
    image: scibite/scibiteai-serving:latest
    ports:
      - 8500:8500
      - 8501:8501
    volumes:
      - ./models:/SciBiteAI
    command:
      - '--model_config_file=/SciBiteAI/model_config.config'
      - '--model_config_file_poll_wait_seconds=-1'
      - '--enable_batching=true'
      - '--batching_parameters_file=/SciBiteAI/batch_params.pb'

  redis:
    container_name: redis-db
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  cron-runner:
    container_name: cron-runner
    build:
      context: ./
      dockerfile: ./config/cron.Dockerfile
    volumes:
      - ./models/:/models/

